version: '3.1'

services: 

  db:
    image: 'postgres:latest'
    container_name:  pg-docker
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: movies
    volumes: 
     - ./Users/zacharyhaines/docker/volumes/postgres:/var/lib/postgresql/data
    networks: 
     - app-network
  
  server: 
    image: server
    container_name: server_container
    build: ./server
    ports:
     - 8080:8080
    networks:
      - app-network
    depends_on:
      - db

  client: 
    image: client
    container_name: client_container
    build: ./client
    ports:
     - "3000:3000"
    networks: 
      - app-network
    depends_on: 
      - server

networks:
  app-network:
    driver: bridge