version: '3.1'

services: 

  db:
    image: 'postgres'
    container_name:  database
    restart: always
    ports: 
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes: 
     - db:/var/lib/postgresql/data
    networks: 
     - app
  
  server: 
    image: server
    container_name: server
    restart: always
    build: ./server
    # volumes:
    #   - "./server:/app"
    ports:
     - 8080:8080
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker:5432/db
    networks:
      - app
    depends_on:
      - db

  client: 
    image: client
    container_name: client
    restart: always
    build: ./client
    # volumes:
    #   - "./client:/app"
    ports:
     - "3000:3000"
    networks: 
      - app
    depends_on: 
      - server

networks:
  app:
    driver: bridge

##############
# On the first invocation of docker-compose up the volume will be created. 
# The same volume will be reused on following invocations. https://docs.docker.com/storage/volumes/
volumes:
  db:
    driver: local